### ISSUE TITLE
Unclear whether "smith pdfs" command is using correct rendering engine

### ISSUE THREAD

**Issue by JBrase** [silnrsi/smith#13]
My wscript has the line
     script = [ "DFLT", "latn", "tavt" ]
The command "smith pdfs" generates output files for Graphite, ot_DFLT, ot_latn, and ot_tavt. But all of the OT files have "using Graphite" in the file header. E.g. The header line for the file "THP-TaiViet_pdfs_ot_DFLT_taiheritagepro-r_ot_DFLT.pdf" is "Test for TaiHeritagePro-R.ttf - /OT:script=DFLT **using Graphite** - 07:47 Fri 03 Feb 2017 CST - XeTeX .9999".
I hope that only the file header is wrong, and that the text has been in fact been rendered with the OT engine.

**Comment by n7s** [comment]
Issue confirmed to still be present. See smithlib/templates.py line 41.

**Comment by mhosken** [comment]
Removed the using graphite/opentype and leave it to the more cryptic info to explain that.

**Comment by devosb** [comment]
Added back in the "using graphite/opentype" bit but fixed (hopefully).
The issue was there are four types of fonts that XeTeX knows about

- TeX
- AAT
- OpenType
- Graphite

The previous code only checked for three of them (omitting AAT).
Now, all four types are checked for.
Details on page 7 at http://mirrors.ibiblio.org/CTAN/info/xetexref/xetex-reference.pdf
