### ISSUE TITLE
Debian frowns upon integration of waf inside source package

### ISSUE THREAD

**Issue by n7s** [silnrsi/smith#33]
Considering this https://lintian.debian.org/tags/source-contains-waf-binary.html

Should we investigate another solution rather than having a debian/bin/smith ?

**Comment by mhosken** [comment]
We could strip out all the self expansion stuff and make smith a conventional python program that has to be installed. It's probably just a case of changing the smith program to run Scripting.waf_entry_point(cwd, VERSION, wafdir) and we could probably refactor out VERSION, and even wafdir given we don't use anything in the waflib/extras dir anyway. So we could drop all that.

**Comment by nrsiward** [comment]
The smith_dev.py script shows that calling Scripting.waf_entry_point() directly works correctly. The script finds 'wafdir' based on the location the script is launched from and hard codes the 'Context.WAFVERSION' value. I suggest we modify the waf_entry_point 'version' argument to default to 'Context.WAFVERSION' and the 'wafdir' argument to 'None' (so any code that might use it will likely throw an exception, but that should not occur using smith). This yields: waf_entry_point(cwd). 

The smith_dev.py script (and waf and smith) only requires the waflib and smithlib directories. We could package smith with a smith folder containing smith_dev.py (renamed to smith.py) and the waflib and smithlib sub-directories (the extras and Tools directories could be excluded from waflib).

To make it even simpler, If we add __init__.py to smithlib, smith.py becomes:
import os
from smithlib import wsiwaf
from waflib import Scripting
Scripting.waf_entry_point(os.getcwd())

I've tested this structure using the tutorial/font6 wscript with configure, build, alltests, zip, and distclean. Everything seemed to work.

Since there is only a small change to Scripting.py, this approach should preserve the ability to still build smith as it is now using mywaflite and waf-light.

**Comment by mhosken** [comment]
What's not to like. Go for it.

**Comment by nrsiward** [comment]
Smith can be now by packaged in the normal Python way. (The old waf way of running mywaflite still works.)

You can run `setup.py sdist` to create a source distribution. After unpacking that, you can change to the unpack folder and run 'sudo setup.py install' and smith will be installed into the system Python and be executable from the command line. Of course, other variations for installing also work, such as `setup.py develop --user' if you want to execute from source.

In the source repo itself, you can run smith.py to run from source. smith_dev.py isn't needed anymore.

**Comment by nrsiward** [comment]
Though smith seems to work with `wafdir` defaulting to None, `wafdir` does actually matter to waf itself. (Running smith in it's own repo with the wscript that builds waf was failing.) So, I undid the changes to `Scripting.waf_entry_point()` and passed the values from smith.py instead. 

While you can run from source by just running smith.py, it's more typical to use `setup.py develop [--user]` to setup execution from source.

**Comment by n7s** [comment]
setup.py metadata has been filled in
