### ISSUE TITLE
Add tarball target

### ISSUE THREAD

**Issue by mhosken** [silnrsi/smith#34]
This target creates a .tar.xz that has the same contents as the zip target, but with linux line endings. It also has the same name as the zipfile but with a different extension.

**Comment by n7s** [comment]
Great!  Seems like it creates a subfolder with the value of out (results in most cases). We probably need to drop that extra subfolder to have the tree structure be in sync with the .zip.

**Comment by n7s** [comment]
This new target has been added to the completion script and the manpage as well.

**Comment by mhosken** [comment]
fixed path problem

**Comment by devosb** [comment]
@bobh0303 writes in #31 "A thought: since it is all the same as the zip, why not just build it as a by-product of the zip target?" A partial response is the zip and the tarball are created with Python modules that have the files added to a Python object one by one, there is no directory that corresponds to the directory layout in the zip or tarball that is being added all at once. There is some common code between smith zip and smith tarball that could be refactored to a common function.
