### ISSUE TITLE
Remove .vfb from smithlib/dot.gitignore

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/smith#40]
Please remove .vfb from the list of files included in the default recommended .gitignore file. Since almost all our projects were once .vfb-based, and we want to include archived copies of those masters in source/archive, having .vfb ignored can cause us to mistakenly neglect to track them in git.

**Comment by n7s** [comment]
I (for one) would argue against keeping opaque legacy formats in a public repository and encouraging people to track and maintain such files. Isn't it better to migrate them to open cross-platform formats for future-proofing? Hence the ignore config default. Since we now have a migration path to an open format what's the rationale for needing the older formats?

**Comment by mhosken** [comment]
Yes, opaque legacy formats are a bad idea. But if they are all you have and they are the authoritative source for the project, they should be kept under version control. Of course this is problematic with regards to merging, but that doesn't preclude them being there. I agree with @jvgaultney that they should be removed from the .gitignore and tracked. In due course .vfb will disappear, but it will never (probably) emerge as another format that we don't want to track. So, again, it is safe to remove from the .gitignore, because if you have it in your project, you want to track it. If you have it in your project and don't want to track it, then keep it in another directory and add that directory to the .gitignore. The aim is that everything in src/ should be tracked as part of the source of the project.

**Comment by n7s** [comment]
Changed in b605978.
